### ISSUE TITLE
Sample console application

### ISSUE THREAD

**Issue by justinyoo** [aliencube/youtube-subtitles-extractor#11]
Add a sample console application that uses all implemented methods.

The use case and flow of this console app scenario is...

1. Run the console app.
2. Wait for the user input of the YouTube video URL.
3. Extract the video details and list available languages (language codes) for the user to choose.
4. Extract and display the subtitle of the user's choice of language code, with the table format of like:

    ```
    Start       End         Subtitle
    12:34:56    12:56:34    Hello World
    12:56:34    13:24:56    Lorem Ipsum
    ```

**Comment by mvillajos** [comment]
Hello, I can work on it, I almost have it done.
